### ISSUE TITLE
startup crash

### ISSUE THREAD

**Issue by slimemc12** [Andrews54757/andrewstechmc-brewer-video#1]
the game lust crashes at startup
using tweakfork 1.1.7
with tweakeroo  tweakeroo-fabric-1.16.4-0.10.0-dev.20210204.204245

**Comment by Andrews54757** [comment]
@slimemc12 Wrong repository

**Comment by Andrews54757** [comment]
Also, tweakfork is a fork that replaces tweakeroo, not an addon that changes it. This means you have to remove old tweakeroo.
